### ISSUE TITLE
Setting Default page at index.

### ISSUE THREAD

**Issue by RobertJGabriel** [skuligowski/md-docs#2]
Hey @skuligowski Is there any way to set the default landing page.

**Comment by RobertJGabriel** [comment]
bump @skuligowski

**Comment by skuligowski** [comment]
Hi @RobertJGabriel , unfortunatelly it's not possible now. 
However it's a good idea worth to implement.

**Comment by RobertJGabriel** [comment]
Ah awesome, I work on something :) For a pr

**Comment by skuligowski** [comment]
#3
